### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by squpshift** [istudko/anchor-withdrawer#1]
Hi thanks a lot for putting this together, can't believe I'm going to withdraw and sell my UST at 2.5% of it's peg value! So sad.

Getting the following error. Any tips?

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:130:10)
    at Object.hash160 (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/crypto.js:15:16)
    at BIP32.get identifier [as identifier] (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:65:23)
    at BIP32.get fingerprint [as fingerprint] (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:68:21)
    at BIP32.derive (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:151:88)
    at BIP32.deriveHardened (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:168:21)
    at /home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:182:31
    at Array.reduce (<anonymous>)
    at BIP32.derivePath (/home/shea/Sites/anchor-withdrawer/node_modules/bip32/src/bip32.js:178:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
```

**Comment by istudko** [comment]
@squpshift try this solution https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
Ps. I use Node.js v16.15.0

**Comment by istudko** [comment]
I'll close the issue since there's no response for a long time. and the issue is not related to the code
